/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 04 18:37:36 GMT 2024
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.LinkedList;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinkedList_ESTest extends LinkedList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      linkedList0.add("A#[J(`<]");
      boolean boolean0 = linkedList0.remove("}}6<I-)E~");
      assertEquals(1, linkedList0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      int int0 = linkedList0.getSize();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) null);
      Integer integer0 = new Integer(1796);
      // Undeclared exception!
      try { 
        linkedList0.remove(integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) null);
      Integer integer0 = new Integer((-725));
      // Undeclared exception!
      try { 
        linkedList0.contains(integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      boolean boolean0 = linkedList0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      boolean boolean0 = linkedList0.isEmpty();
      assertEquals(1, linkedList0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("A#[J(`<]");
      boolean boolean0 = linkedList0.contains("A#[J(`<]");
      assertEquals(1, linkedList0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      boolean boolean0 = linkedList0.contains("A#[J(`<]");
      assertEquals(1, linkedList0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      linkedList0.add("A#[J(`<]");
      boolean boolean0 = linkedList0.remove("i;");
      assertEquals(2, linkedList0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      linkedList0.add("A#[J(`<]");
      boolean boolean0 = linkedList0.remove("A#[J(`<]");
      assertEquals(1, linkedList0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      boolean boolean0 = linkedList0.remove((Integer) null);
      assertFalse(boolean0);
      assertTrue(linkedList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("}}6<I-)E~");
      linkedList0.add("A#[J(`<]");
      linkedList0.add("A#[J(`<]");
      assertEquals(3, linkedList0.getSize());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      int int0 = linkedList0.getSize();
      assertEquals(0, int0);
  }
}
